version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
  jobs:
    pre_build:
      - python docs/source/scripts/build_supported_types.py

sphinx:
  fail_on_warning: true
  configuration: docs/source/conf.py

formats:
  - pdf
  - epub

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
