name: Release

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade build
          pip install -r requirements.txt
          pip install -r docs/requirements.txt
          pip install setuptools wheel twine
      - name: Check branch/version
        run: |
          make lint-release
      - name: Check docs can compile
        run: |
          make docs
      - name: Build marsh
        run: |
          python -m build --no-isolation
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
